
name: Deployment1

on:
  push:
    branches: development 
jobs:
  
  Build_Development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM
        run: sudo npm install -g npm@8.15.1

      - name: Set legacy-peer-deps
        run: sudo npm config set legacy-peer-deps true

      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force


      - name: Buid the application
        env:
          CI: false
        run: npm run build:dev
        
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-development
          path: build
  Deploy_Development:
    needs: Build_Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-development
          path: build
      - name: Deploy to Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.Bhutan_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.Bhutan_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.Bhutan_HOSTNAME }}:/tmp/bhutan_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.Bhutan_HOSTNAME }} '
            cd /var/www/html/Bhutan-FE &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development '
 
            

      
  
